import {Hono} from 'hono';
import {setCookie,getCookie,deleteCookie} from 'hono/cookie';
import {clean,validEmail,validPhone,leadTier,scoreLead,canTransition,LEAD_STATUSES,RFQ_STATUSES} from './domain.js';
import {sameOrigin,rateLimit,ip,securityHeaders} from './security.js';
const app=new Hono();
app.use('*',async(c,next)=>{await next();securityHeaders(c.res);});
const json=(c,b,s=200)=>c.json(b,s);
async function audit(c,action,type,id,meta={}){await c.env.DB.prepare('INSERT INTO audit_log(id,admin_user_id,action,entity_type,entity_id,metadata,ip_address) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),c.get('adminId')||null,action,type,id,JSON.stringify(meta),ip(c)).run();}
async function admin(c,next){const sid=getCookie(c,'ail_admin');if(!sid)return json(c,{error:'Unauthorized'},401);const row=await c.env.DB.prepare("SELECT admin_users.id,username FROM admin_sessions JOIN admin_users ON admin_users.id=admin_sessions.admin_user_id WHERE admin_sessions.id=? AND expires_at>datetime('now')").bind(sid).first();if(!row)return json(c,{error:'Unauthorized'},401);c.set('adminId',row.id);c.set('adminUser',row.username);return next();}
app.get('/api/health',c=>json(c,{ok:true,service:'ail-labs-b2b-os'}));
app.get('/api/products',async c=>json(c,{products:(await c.env.DB.prepare('SELECT id,name,category,description FROM products WHERE active=1 ORDER BY category,name').all()).results||[]}));
app.post('/api/leads',async c=>{if(!sameOrigin(c)||!(await rateLimit(c,ip(c),10)))return json(c,{error:'Request tidak diizinkan'},429);const b=await c.req.json().catch(()=>({}));const name=clean(b.name,120),company=clean(b.company,160),wa=clean(b.whatsapp,30),email=clean(b.email,180).toLowerCase();if(!name||!company||!validEmail(email)||!validPhone(wa)||b.consent!==true)return json(c,{error:'Data kontak atau consent tidak valid'},400);const id=crypto.randomUUID(),score=scoreLead([{type:'inquiry'}]);await c.env.DB.prepare('INSERT INTO leads(id,name,company,whatsapp,email,product_interest,source,landing_page,visited_pages,consent_at,status,score,tier) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,name,company,wa,email,clean(b.product_interest,200),clean(b.source||'website',100),clean(b.landing_page||'/',300),clean(JSON.stringify(b.visited_pages||[]),2000),new Date().toISOString(),'New',score,leadTier(score)).run();await c.env.DB.prepare('INSERT INTO lead_events(id,lead_id,event_type,score_delta,metadata) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,'inquiry',30,'{}').run();return json(c,{ok:true,lead_id:id,score,tier:leadTier(score)},201);});
app.post('/api/leads/:id/events',async c=>{if(!sameOrigin(c)||!(await rateLimit(c,ip(c),30)))return json(c,{error:'Rate limit'},429);const b=await c.req.json().catch(()=>({})),type=clean(b.type,60),allowed=['catalog_view','product_view','catalog_download','inquiry','contact_verified','quotation_request'];if(!allowed.includes(type))return json(c,{error:'Event tidak valid'},400);const lead=await c.env.DB.prepare('SELECT id FROM leads WHERE id=?').bind(c.req.param('id')).first();if(!lead)return json(c,{error:'Lead tidak ditemukan'},404);const delta={catalog_view:5,product_view:10,catalog_download:15,inquiry:30,contact_verified:20,quotation_request:40}[type];await c.env.DB.prepare('INSERT INTO lead_events(id,lead_id,event_type,score_delta,metadata) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),lead.id,type,delta,'{}').run();const x=await c.env.DB.prepare('SELECT COALESCE(SUM(score_delta),0) score FROM lead_events WHERE lead_id=?').bind(lead.id).first(),score=Math.min(100,Number(x.score));await c.env.DB.prepare("UPDATE leads SET score=?,tier=?,updated_at=datetime('now') WHERE id=?").bind(score,leadTier(score),lead.id).run();return json(c,{ok:true,score,tier:leadTier(score)});});
app.get('/api/admin/leads',admin,async c=>{const s=clean(c.req.query('status'),30),q=s?c.env.DB.prepare('SELECT * FROM leads WHERE status=? ORDER BY score DESC,created_at DESC').bind(s):c.env.DB.prepare('SELECT * FROM leads ORDER BY score DESC,created_at DESC');return json(c,{leads:(await q.all()).results||[]});});
app.patch('/api/admin/leads/:id/status',admin,async c=>{const to=clean((await c.req.json().catch(()=>({}))).status,30),row=await c.env.DB.prepare('SELECT status FROM leads WHERE id=?').bind(c.req.param('id')).first();if(!row||!LEAD_STATUSES.includes(to)||!canTransition('lead',row.status,to))return json(c,{error:'Transisi lead tidak diizinkan'},409);await c.env.DB.prepare("UPDATE leads SET status=?,updated_at=datetime('now') WHERE id=?").bind(to,c.req.param('id')).run();await audit(c,'lead.status','lead',c.req.param('id'),{from:row.status,to});return json(c,{ok:true,status:to});});
app.post('/api/rfqs',async c=>{if(!sameOrigin(c)||!(await rateLimit(c,ip(c),10)))return json(c,{error:'Request tidak diizinkan'},429);const b=await c.req.json().catch(()=>({})),items=Array.isArray(b.items)?b.items:[],company=clean(b.company,160),email=clean(b.email,180).toLowerCase(),wa=clean(b.whatsapp,30);if(!company||!validEmail(email)||!validPhone(wa)||!items.length||b.verified!==true||b.consent!==true)return json(c,{error:'RFQ membutuhkan kontak valid, item, verifikasi dan consent'},400);for(const x of items)if(!clean(x.product_id,80)||!Number.isInteger(Number(x.qty))||Number(x.qty)<1)return json(c,{error:'Item RFQ tidak valid'},400);const id=crypto.randomUUID();await c.env.DB.prepare('INSERT INTO rfqs(id,lead_id,company,whatsapp,email,status,notes,verified_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,clean(b.lead_id,80)||null,company,wa,email,'Draft',clean(b.notes,1000),new Date().toISOString()).run();for(const x of items)await c.env.DB.prepare('INSERT INTO rfq_items(id,rfq_id,product_id,qty) VALUES(?,?,?,?)').bind(crypto.randomUUID(),id,clean(x.product_id,80),Number(x.qty)).run();await c.env.DB.prepare('INSERT INTO rfq_history(id,rfq_id,from_status,to_status,note) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),id,null,'Draft','RFQ dibuat').run();return json(c,{ok:true,rfq_id:id},201);});
app.get('/api/admin/rfqs',admin,async c=>json(c,{rfqs:(await c.env.DB.prepare('SELECT r.*,COUNT(i.id) item_count FROM rfqs r LEFT JOIN rfq_items i ON i.rfq_id=r.id GROUP BY r.id ORDER BY r.created_at DESC').all()).results||[]}));
app.patch('/api/admin/rfqs/:id/status',admin,async c=>{const b=await c.req.json().catch(()=>({})),to=clean(b.status,30),row=await c.env.DB.prepare('SELECT status FROM rfqs WHERE id=?').bind(c.req.param('id')).first();if(!row||!RFQ_STATUSES.includes(to)||!canTransition('rfq',row.status,to))return json(c,{error:'Transisi RFQ tidak diizinkan'},409);await c.env.DB.prepare("UPDATE rfqs SET status=?,updated_at=datetime('now') WHERE id=?").bind(to,c.req.param('id')).run();await c.env.DB.prepare('INSERT INTO rfq_history(id,rfq_id,from_status,to_status,note) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),c.req.param('id'),row.status,to,clean(b.note,1000)).run();await audit(c,'rfq.status','rfq',c.req.param('id'),{from:row.status,to});return json(c,{ok:true,status:to});});
function csv(rows,name){const cols=Object.keys(rows[0]||{id:''}),body=[cols,...rows.map(r=>cols.map(k=>String(r[k]??'').replaceAll('"','""')))].map(a=>a.map(v=>'"'+v+'"').join(',')).join('\n');return new Response(body,{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename='+name}});}
app.get('/api/admin/leads.csv',admin,async c=>csv((await c.env.DB.prepare('SELECT id,name,company,whatsapp,email,product_interest,status,score,tier,source,created_at FROM leads ORDER BY created_at DESC').all()).results||[],'leads.csv'));
app.get('/api/admin/rfqs.csv',admin,async c=>csv((await c.env.DB.prepare('SELECT id,company,whatsapp,email,status,created_at,updated_at FROM rfqs ORDER BY created_at DESC').all()).results||[],'rfqs.csv'));
app.post('/api/admin/login',async c=>{if(!(await rateLimit(c,ip(c),5,300)))return json(c,{error:'Terlalu banyak percobaan'},429);const b=await c.req.json().catch(()=>({})),row=await c.env.DB.prepare('SELECT id,username,password_hash FROM admin_users WHERE username=?').bind(clean(b.username,80)).first();if(!row)return json(c,{error:'Login gagal'},401);const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(b.password||''))),got=[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');if(got!==row.password_hash)return json(c,{error:'Login gagal'},401);const sid=crypto.randomUUID();await c.env.DB.prepare("INSERT INTO admin_sessions(id,admin_user_id,expires_at) VALUES(?,?,datetime('now','+8 hours'))").bind(sid,row.id).run();setCookie(c,'ail_admin',sid,{httpOnly:true,secure:true,sameSite:'Strict',path:'/',maxAge:28800});return json(c,{ok:true});});
app.post('/api/admin/logout',admin,async c=>{const sid=getCookie(c,'ail_admin');await c.env.DB.prepare('DELETE FROM admin_sessions WHERE id=?').bind(sid).run();deleteCookie(c,'ail_admin',{path:'/'});return json(c,{ok:true});});
app.get('/api/admin/me',admin,async c=>json(c,{ok:true,user:c.get('adminUser')}));
app.get('/api/admin/dashboard',admin,async c=>json(c,{leads:await c.env.DB.prepare("SELECT COUNT(*) total,COALESCE(SUM(tier='HOT'),0) hot FROM leads").first(),rfqs:await c.env.DB.prepare("SELECT COUNT(*) total,COALESCE(SUM(status IN ('Sent','Negotiation') AND updated_at<datetime('now','-24 hours')),0) overdue FROM rfqs").first()}));
app.notFound(c=>c.req.path.startsWith('/api/')?json(c,{error:'Not found'},404):c.env.ASSETS.fetch(c.req.raw));
export default {fetch:app.fetch,scheduled:async(_c,env)=>{const r=await env.DB.prepare("SELECT id FROM rfqs WHERE status IN ('Sent','Negotiation') AND updated_at<datetime('now','-24 hours')").all();console.log('RFQ overdue',r.results?.length||0);}};